### PR TITLE
fix: use libc::c_ulong instead of u64 for ioctl request codes

### PR DESCRIPTION
**Pull request by chris-ricketts**
Fixes the build for 32bit targets

### CODE REVIEW

**Comment by Wodann** [comment]
Thanks for the PR. It all looks good, but I just want to test it on my 64-bit windows and ubuntu setups to check that everything is okay before I merge :)

**Comment by chris-ricketts** [comment]
No problem. 

To get `io_bluetooth` to build for 32bit ARM I also had to change [the IREQ_CACHE_FLUSH constant](https://github.com/Wodann/libbluetooth-rs/blob/17c5d62fc7c858ad845d17e53478d0aade91b6a7/src/hci.rs#L2087) to a `libc::c_long` as well. 
I think ideally the `libbluetooth` bindings should be generated using [bindgen](https://github.com/rust-lang/rust-bindgen) as all these cross-platform considerations are done automatically. 

`io_bluetooth` is working really well for my project, it is so much more reliable than the `rfcomm` CLI tool. Thanks for your hard work on this.

**Comment by Wodann** [comment]
Thanks, I am glad you are finding a good use for it.

I'm working on `bindgen` integration, as that indeed is a more permanent solution 👌

**Comment by Wodann** [comment]
@chris-ricketts I implemented auto-generation using bindgen in the `feature/bindgen` branch and integrated it in `io-bluetooth`. Would you mind trying the new version? It's on the following branch: https://github.com/Wodann/io-bluetooth-rs/tree/feature/libbluetooth-v0.2.0

If everything also works on your 32-bit system, I'll go ahead and release it.

**Comment by chris-ricketts** [comment]
Hi @Wodann - sorry for the delayed reply.

I get the following when compiling for 32bit ARM using [cross](https://github.com/rust-embedded/cross)
```
error: failed to run custom build command for `libbluetooth v0.2.0 (https://github.com/wodann/libbluetooth-rs.git?branch=feature/bindgen#64a7a243)`

Caused by:
  process didn't exit successfully: `/target/release/build/libbluetooth-750d6f12d6f5f9b3/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: CrossCompilation', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

I suspect it is this line: 
```rust
let library = pkg_config::probe_library("bluez").unwrap();
```

When setting the `PKG_CONFIG_ALLOW_CROSS` I get:
```
error: failed to run custom build command for `libbluetooth v0.2.0 (https://github.com/wodann/libbluetooth-rs.git?branch=feature/bindgen#64a7a243)`

Caused by:
  process didn't exit successfully: `/target/release/build/libbluetooth-750d6f12d6f5f9b3/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"bluez\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package bluez was not found in the pkg-config search path.\nPerhaps you should add the directory containing `bluez.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'bluez\' found\n" } }', src/libcore/result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Although it might seem less 'clean', I think you would be better including the bluetooth header files within the source tree and then linking by passing flags directly to `rustc` like so:
```rust
println!("cargo:rustc-link-lib=bluetooth")
```

That avoids the extra dependency on `pkg-config` and will make the build more portable.

**Comment by Wodann** [comment]
Thank you for trying it out. I will try to make it work for cross-compilation too. Ideally I don't want to lock the build script to included header files, so I'll see if there is another workaround.

I'll get back to you asap.

**Comment by Wodann** [comment]
@chris-ricketts I tried resolving your aforementioned issue and I am pretty sure this is a result of the docker image not having `libbluetooth-dev` installed. There are two ways of avoiding this from happening but they both have caveats:

1) Create a custom docker image that includes `libbluetooth-dev` and I'll add a `Cross.toml` file that references this
2) Add C headers to `libbluetooth` as a fallback

Option 1 ties the user to a specific version of the cross DockerImage, whereas option 2 ties the user to a specific `bluez` version.

Alternatively, I just add a section to the ReadMe telling people that they need to have `libbluetooth-dev` installed on their DockerImage when cross-compiling, which is also the case for normal compilation.

**Comment by chris-ricketts** [comment]
Hi @Wodann the docker image I tested with had `libbluetooth-dev:armhf` installed but not for the host architecture. Running `arm-linux-gnueabihf-pkg-config --libs bluez` returns the correct flags but `pkg-config` cannot find it.

I will try it again after installing `libbluetooth-dev` for the host arch as well so the regular `pkg-config` binary can find the headers directory - it should still link to the `armhf` version. 

I don't know why I didn't think of this before - its definitely cleaner to leave the headers out of the tree where possible.

**Comment by Wodann** [comment]
Thank you for your help figuring out a permanent solution :)

I would have thought that `cross` only requires the target system's libraries

**Comment by chris-ricketts** [comment]
Hi @Wodann - I got it to build using cross! I just had to add set `PKG_CONFIG_ALLOW_CROSS` and `PKG_CONFIG_PATH` to the arm pkg config directory. 

I also had to make the following change to [this line](https://github.com/Wodann/io-bluetooth-rs/blob/43c17b4514712202d97cc1bef44a3c29fbeb9578/src/sys/unix/bt.rs#L349):
```rust 
libbt::IREQ_CACHE_FLUSH as libc::c_long
```

**Comment by Wodann** [comment]
Hi @chris-ricketts. Sorry for the delayed response; I was on vacation.

I made some updates to the [`io-bluetooth-rs`](https://github.com/Wodann/io-bluetooth-rs) repository, including a Github Actions CI workflow. That way I can easily check that my changes work across different platforms.

I want to release a version 0.2.0 with the changes that fix your problem, but before I merge the PR could you please check that this branch works for you too? https://github.com/Wodann/io-bluetooth-rs/tree/feature/libbluetooth-v0.2.0

Thank you so much for your continued help and effort!

**Comment by ChrisCA** [comment]
Hi,

@Wodann I checked your branch with bindgen on a Raspberry Pi 4. It build successfully and I also successfully scanned and connected to a BT device.
However I really struggled a bit to with a few build failures which in the end were related to missing dependencies.
While I've seen you check in the bindings lib for libbluetooth-dev, I additionally needed to install _llvm-dev_ and _clang_ as a dependency. I'm not sure whether it's just depending on my unique system configuration or whether it's worth to add a hint in the docs as well as extending the build.rs with said dependencies.

Feel free to ask if you need more information.

**Review by Wodann — APPROVED** [review]

**Comment by Wodann** [comment]
I decided to merge this for the time being, as - based on @ChrisCA's feedback- it's proving a lot more difficult to get this to work with auto-generated bindings. I created an implementation that generates the bindings per request. That way it doesn't force people to have llvm installed.

The generated bindings are way too big imo, so I am trying to see if I can restrict generated bindings. As this fix is already long overdue, I'm including it in a temporary release though.

**Comment by Wodann** [comment]
@ChrisCA Thanks for your feedback and offer. I tried to incorporate it in the CLI tool that I described above, but I think that approach might take a little more time. The downside of handwritten bindings or generated bindings with whitelisting is that you might miss important types or functions when the sources are updated.

That can be resolved by using a build script or CLI tool, but then the bindings are very large and nondescript. If you have any preference w.r.t. that, please let me know.

**Comment by ChrisCA** [comment]
Thanks for the merge. Would be great to also bump the io-bluetooth crate, in case this is necessary.
I just started to use io-bluetooth in a side project after I checked the general usability. So I would be happy to further constribute feedback to io-bluetooth and libbluetooth after I gained some more feedback from the field.
So for the time being I've no preference but this might change in the next months.

**Comment by Wodann** [comment]
Sounds good. Will do!

**Pull request merged**
